-- MySQL Script generated by MySQL Workbench
-- Fri Mar 11 14:18:52 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema weiyunmei
-- -----------------------------------------------------
-- 微云媒数据库

-- -----------------------------------------------------
-- Schema weiyunmei
--
-- 微云媒数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weiyunmei` DEFAULT CHARACTER SET utf8 ;
USE `weiyunmei` ;

-- -----------------------------------------------------
-- Table `weiyunmei`.`advertisement_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`advertisement_type` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`advertisement_type` (
  `id` VARCHAR(50) NOT NULL COMMENT '广告创建时间',
  `name` VARCHAR(45) NULL COMMENT '类型名称',
  `remark` VARCHAR(200) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
PACK_KEYS = Default;


-- -----------------------------------------------------
-- Table `weiyunmei`.`enterprise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`enterprise` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`enterprise` (
  `id` VARCHAR(50) NOT NULL,
  `login_name` VARCHAR(45) NULL COMMENT '登录账号',
  `password` VARCHAR(45) NULL COMMENT '登录密码',
  `name` VARCHAR(45) NULL COMMENT '企业名称',
  `email` VARCHAR(45) NULL COMMENT '企业邮箱',
  `contacts` VARCHAR(45) NULL COMMENT '联系人',
  `phone` VARCHAR(18) NULL COMMENT '联系电话',
  `payment_card` VARCHAR(45) NULL COMMENT '银行卡号',
  `alipay` VARCHAR(45) NULL COMMENT '支付宝',
  `business_license` VARCHAR(200) NULL COMMENT '营业执照',
  `identity_card_face` VARCHAR(200) NULL COMMENT '身份证',
  `identity_card_back` VARCHAR(200) NULL COMMENT '身份证，背面',
  `money` BIGINT NULL COMMENT '账户余额',
  `frozen_money` BIGINT NULL COMMENT '冻结金额',
  `consume_money` BIGINT NULL COMMENT '历史消费金额',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weiyunmei`.`advertisement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`advertisement` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`advertisement` (
  `id` VARCHAR(50) NOT NULL COMMENT 'id',
  `title` VARCHAR(200) NULL COMMENT '标题',
  `icon` VARCHAR(200) NULL COMMENT '图标',
  `simple_descript` VARCHAR(200) NULL COMMENT '简述',
  `type` VARCHAR(50) NULL COMMENT '任务类型',
  `money_count` BIGINT NULL COMMENT '总奖金',
  `money` INT NULL COMMENT '任务金额',
  `company_proportion` INT NULL COMMENT '分成比例，公司',
  `user_proportion` INT NULL COMMENT '分成比例 - 用户',
  `start_time` BIGINT NULL COMMENT '任务开始时间',
  `end_time` BIGINT NULL COMMENT '任务结束时间',
  `release_enterprise` VARCHAR(50) NULL COMMENT '发布企业',
  `execution_flow` TEXT NULL COMMENT '执行流程',
  `details` TEXT NULL COMMENT '详细描述',
  `execution_address` VARCHAR(200) NULL COMMENT '任务执行地址',
  `is_examine` INT NULL DEFAULT 1 COMMENT '是否需要人工审核 0 不需要/1需要',
  `status` INT NULL COMMENT '广告状态',
  `create_time` BIGINT NULL COMMENT '广告创建时间',
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`type` ASC),
  INDEX `enterprise_id_key_idx` (`release_enterprise` ASC),
  CONSTRAINT `advertisement_type_key`
    FOREIGN KEY (`type`)
    REFERENCES `weiyunmei`.`advertisement_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `enterprise_id_key`
    FOREIGN KEY (`release_enterprise`)
    REFERENCES `weiyunmei`.`enterprise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weiyunmei`.`advertisement_data_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`advertisement_data_type` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`advertisement_data_type` (
  `id` VARCHAR(50) NOT NULL COMMENT 'id',
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weiyunmei`.`advertisement_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`advertisement_data` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`advertisement_data` (
  `id` VARCHAR(50) NOT NULL COMMENT 'id',
  `label` VARCHAR(10) NULL COMMENT '数据label',
  `name` VARCHAR(200) NULL COMMENT '数据名称',
  `type` VARCHAR(45) NULL COMMENT '数据类型',
  `advertisement_id` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`advertisement_id` ASC),
  INDEX `type_key_idx` (`type` ASC),
  CONSTRAINT `advertisement_id_key`
    FOREIGN KEY (`advertisement_id`)
    REFERENCES `weiyunmei`.`advertisement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `type_key`
    FOREIGN KEY (`type`)
    REFERENCES `weiyunmei`.`advertisement_data_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weiyunmei`.`enterprise_consume_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`enterprise_consume_log` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`enterprise_consume_log` (
  `id` VARCHAR(50) NOT NULL COMMENT 'id',
  `create_time` BIGINT NULL COMMENT '扣款时间',
  `money` BIGINT NULL COMMENT '扣款金额',
  `remark` VARCHAR(45) NULL COMMENT '备注信息',
  `enterprise_id` VARCHAR(50) NULL COMMENT '企业id',
  `advertisement_id` VARCHAR(50) NULL COMMENT '广告id',
  PRIMARY KEY (`id`),
  INDEX `enterprise_consume_log_enterprise_key_idx` (`enterprise_id` ASC),
  INDEX `enterprise_consume_log_advertisement_key_idx` (`advertisement_id` ASC),
  CONSTRAINT `enterprise_consume_log_enterprise_key`
    FOREIGN KEY (`enterprise_id`)
    REFERENCES `weiyunmei`.`enterprise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `enterprise_consume_log_advertisement_key`
    FOREIGN KEY (`advertisement_id`)
    REFERENCES `weiyunmei`.`advertisement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weiyunmei`.`enterprise_recharge_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`enterprise_recharge_log` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`enterprise_recharge_log` (
  `id` VARCHAR(50) NOT NULL COMMENT 'id',
  `create_time` BIGINT NULL COMMENT '充值时间',
  `money` BIGINT NULL COMMENT '充值金额',
  `remark` VARCHAR(45) NULL COMMENT '备注信息',
  `enterprise_id` VARCHAR(50) NULL COMMENT '企业id',
  PRIMARY KEY (`id`),
  INDEX `enterprise_consume_log_enterprise_key_idx` (`enterprise_id` ASC),
  CONSTRAINT `enterprise_recharge_log_enterprise_key0`
    FOREIGN KEY (`enterprise_id`)
    REFERENCES `weiyunmei`.`enterprise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weiyunmei`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`user` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`user` (
  `id` VARCHAR(50) NOT NULL COMMENT '用户id',
  `icon` VARCHAR(200) NULL COMMENT '用户头像',
  `name` VARCHAR(45) NULL COMMENT '用户姓名',
  `sex` VARCHAR(5) NULL COMMENT '性别',
  `mobile` VARCHAR(20) NULL COMMENT '手机号',
  `wechat_id` VARCHAR(45) NULL COMMENT '用户的openID，微信',
  `wechat_name` VARCHAR(45) NULL COMMENT '微信姓名',
  `birthday` BIGINT NULL COMMENT '生日',
  `address` VARCHAR(200) NULL COMMENT '地址',
  `parent_id` VARCHAR(50) NULL COMMENT '上级粉丝',
  `total_money` BIGINT NULL COMMENT '累计收益',
  `money` BIGINT NULL COMMENT '账户余额',
  `create_time` BIGINT NULL COMMENT '创建时间',
  `password` VARCHAR(45) NULL COMMENT '登录密码',
  PRIMARY KEY (`id`),
  INDEX `parent_user_key_idx` (`parent_id` ASC),
  CONSTRAINT `parent_user_key`
    FOREIGN KEY (`parent_id`)
    REFERENCES `weiyunmei`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weiyunmei`.`user_advertisement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`user_advertisement` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`user_advertisement` (
  `id` VARCHAR(50) NOT NULL,
  `advertisement_id` VARCHAR(50) NULL,
  `status` INT NULL COMMENT '任务状态',
  `user` VARCHAR(50) NULL COMMENT '所属用户',
  PRIMARY KEY (`id`),
  INDEX `user_advertisement_key_idx` (`advertisement_id` ASC),
  INDEX `user_advertisement_user_key_idx` (`user` ASC),
  CONSTRAINT `user_advertisement_key`
    FOREIGN KEY (`advertisement_id`)
    REFERENCES `weiyunmei`.`advertisement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_advertisement_user_key`
    FOREIGN KEY (`user`)
    REFERENCES `weiyunmei`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weiyunmei`.`user_advertisement_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`user_advertisement_log` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`user_advertisement_log` (
  `id` VARCHAR(50) NOT NULL,
  `user_advertisement_id` VARCHAR(50) NULL COMMENT '用户任务id',
  `create_time` BIGINT NULL COMMENT '创建时间',
  `status` INT NULL COMMENT '状态',
  `remark` VARCHAR(100) NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  INDEX `user_advertisement_execute_log_key_idx` (`user_advertisement_id` ASC),
  CONSTRAINT `user_advertisement_execute_log_key`
    FOREIGN KEY (`user_advertisement_id`)
    REFERENCES `weiyunmei`.`user_advertisement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weiyunmei`.`user_advertisement_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`user_advertisement_data` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`user_advertisement_data` (
  `id` VARCHAR(50) NOT NULL,
  `advertisement_data_id` VARCHAR(50) NULL COMMENT '提交的数据label',
  `user_advertisement_id` VARCHAR(50) NULL COMMENT '数据所属任务',
  `value` VARCHAR(100) NULL COMMENT '提交的数据',
  PRIMARY KEY (`id`),
  INDEX `fk_user_advertisement_data_user_advertisement1_idx` (`user_advertisement_id` ASC),
  INDEX `fk_user_advertisement_data_advertisement_data1_idx` (`advertisement_data_id` ASC),
  CONSTRAINT `fk_user_advertisement_data_user_advertisement1`
    FOREIGN KEY (`user_advertisement_id`)
    REFERENCES `weiyunmei`.`user_advertisement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_advertisement_data_advertisement_data1`
    FOREIGN KEY (`advertisement_data_id`)
    REFERENCES `weiyunmei`.`advertisement_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weiyunmei`.`user_consume_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`user_consume_log` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`user_consume_log` (
  `id` VARCHAR(50) NOT NULL COMMENT 'id',
  `create_time` BIGINT NULL COMMENT '收益时间',
  `money` BIGINT NULL COMMENT '收益金额',
  `remark` VARCHAR(45) NULL COMMENT '备注信息',
  `user_id` VARCHAR(50) NOT NULL,
  `user_advertisement_id` VARCHAR(50) NOT NULL,
  `type` INT NULL COMMENT '收益类型',
  `fans_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_consume_log_user1_idx` (`user_id` ASC),
  INDEX `fk_user_consume_log_user_advertisement1_idx` (`user_advertisement_id` ASC),
  INDEX `fk_user_consume_log_user2_idx` (`fans_id` ASC),
  CONSTRAINT `fk_user_consume_log_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `weiyunmei`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_consume_log_user_advertisement1`
    FOREIGN KEY (`user_advertisement_id`)
    REFERENCES `weiyunmei`.`user_advertisement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_consume_log_user2`
    FOREIGN KEY (`fans_id`)
    REFERENCES `weiyunmei`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weiyunmei`.`user_cashing_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`user_cashing_log` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`user_cashing_log` (
  `id` VARCHAR(50) NOT NULL COMMENT 'id',
  `create_time` BIGINT NULL COMMENT '提现时间',
  `money` BIGINT NULL COMMENT '提现金额',
  `remark` VARCHAR(45) NULL COMMENT '备注信息',
  `order_no` VARCHAR(45) NULL COMMENT '提现流水号',
  `wechat_order_no` VARCHAR(200) NULL COMMENT '微信订单号',
  `user_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_recharge_log_copy1_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_recharge_log_copy1_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `weiyunmei`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weiyunmei`.`site_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weiyunmei`.`site_admin` ;

CREATE TABLE IF NOT EXISTS `weiyunmei`.`site_admin` (
  `id` VARCHAR(50) NOT NULL COMMENT '管理员id',
  `loginname` VARCHAR(45) NULL COMMENT '登录名',
  `password` VARCHAR(45) NULL COMMENT '登录密码',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
